title: 📘 Graficación - Documentación
description: Apuntes y prácticas del curso de Graficación

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

nav:
  - name: Inicio
    link: /
  - name: Documentación
    link: /docs/
  - name: Repositorio
    link: https://github.com/docpoosersel/Graficacion-Documentacion
