title: 游닂 Graficaci칩n - Documentaci칩n
description: Apuntes y pr치cticas del curso de Graficaci칩n

remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
  - jekyll-remote-theme

markdown: kramdown

just_the_docs:
  theme_mode: dark
  logo: false
  search_enabled: true
  aux_links:
    "Ver en GitHub":
      - "https://github.com/docpoosersel/Graficacion-Documentacion"

highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
